### ISSUE TITLE
Add multiple $and mixin

### ISSUE THREAD

**Issue by danieltorrer** [sass-mq/sass-mq#109]
I'm trying to code something like this `@media only screen and (min-width:460px) and (max-aspect-ratio: 13/9)` . I cant find in the docs how to achieve that. I tried passing its values in an array `@include mq($until: mobile , $and: ['(orientation: portrait)', '(max-aspect-ratio: 13/9)'])` with no luck. Is it possible? Thanks

**Comment by kaelig** [comment]
Hi @danieltorrer, thank you for using sass-mq!

Have you tried having all the `and` statements inside a single string?

```scss
@include mq(
  $until: mobile,
  $and: '(orientation: portrait) and (max-aspect-ratio: 13/9)'
) {
  .foo { border: 0; }
}
```

And would it work for your use-case?
