### ISSUE TITLE
Creating a custom device specific breakpoint

### ISSUE THREAD

**Issue by weinde** [sass-mq/sass-mq#135]
Hey 

I'm just wondering is it possible to create a breakpoint that has width and height and also device pixel ratio predefined
Example of outputed css i want:

```css
@media only screen and (min-width: 1024px) and (max-height: 1366px) and (-webkit-min-device-pixel-ratio: 1.5) and (hover: none) {
   /*css is here*/
}
```

How would one go about creating such an mq-breakpoint?

**Comment by mcaskill** [comment]
I haven't used my fork in a while 😅 buy it might provide some assistance: https://github.com/mcaskill/sass-mq

**Comment by kaelig** [comment]
For complex/composed media queries such as the one you're looking to have as a predefined setting, I'd recommend using a custom mixin (which could wrap sass-mq), a fork of sass-mq, or even another library entirely.

Alternatively, you could do this:

```scss
$custom-preset: (max-height: 1366px) and (-webkit-min-device-pixel-ratio: 1.5) and (hover: none);

@include mq($from: desktop, $and: $custom-preset) {}
``` 

I hope this helps!
