### ISSUE TITLE
Redesign and update library

### ISSUE THREAD

**Issue by area73** [sass-mq/sass-mq#143]
### Deprecation of `@import` and global vars and addition of new functionalities

with the addition of new functionalities on dart sass compiler , this library starts to get deprecation warnings and will probably stop working by October 2022.

[Read more in this post](https://www.sasscss.com/blog/the-module-system-is-launched)

> One year after this deprecation goes into effect (1 October 2022 at latest), we will drop support for @import and most global > functions entirely. This will involve a major version release for all implementations

### Abandon of sass engines other than dart-sass

Also since now there were 3 different sass compilers but it look that now there will be only one maintained (dart sass), so this makes unnecessary to maintain test and compatibility with the other two sass engines:

**Current Releases for sass engines are:**
**Dart Sass 1.34.0**: Dart Sass is the primary implementation of Sass, which means it gets new features before any other
implementation. Also currently is the only one maintain

**LibSass 3.6.5**: LibSass is Deprecated

**Ruby Sass** ⚰
Ruby Sass was the original implementation of Sass, but it reached its end of life as of 26 March 2019. It's no longer supported, and Ruby Sass users should migrate to another implementation.

### Drop compatibility of old browsers
This library has some backward compatibilities with very, very old browsers (IE8) that didn't support media queries and it looks reasonable that we could get read of this compatibility

### Redesign
Whit all these things said, it looks that a redesign / rethinking of this library may need it to be done

## Checkpoints

Bellow I will list some checkpoint that I detect that can be done in this library, probably there are some more and maybe not all these points are the best approach, I just put it here to discuss them.

* [ ] Remove `$mq-base-font-size` since it is deprecated
* [ ] Remove `$mq-responsive` (Drop compatibility of old browsers)
* [ ] `$mq-breakpoints` maybe we can use build in module `sass.map`
* [ ] global functions will not be allow in the future so we should change thinks like `map-has-key(..)` in favor of  `map.has-key(...)`
* [ ] drop test for sass engines other than dart-sass
* [ ] regenerate readme and docs with ifn about using `@use`
* [ ] add compatibility for using this library with `@import` instead of `@use` (this can be easily done by using `@forward` directive)

## Bibliography
[the module system is launched](https://www.sasscss.com/blog/the-module-system-is-launched)
[libsass is deprecated](https://www.sasscss.com/blog/libsass-is-deprecated)
[sass built in modules](https://sass-lang.com/documentation/modules)

**Comment by area73** [comment]
@kaelig , I can work on above points if you like, since I have already some experience working with sass modules, I'm open to any suggestion !

**Comment by joshdavenport** [comment]
These changes sound great, been using this library in projects for longer than I can remember so would hate to see it fall into a black hole of compatibility issues.

Perhaps in the meantime we can address some of the potentially breaking changes upcoming to Dart Sass? The division issue specifically seems like something that needs to happen. Something like:

```
@use "sass:meta"; // Include sass:meta to allow inspection of available sass features
@use "sass:math"; // Include sass:math so math.div is available
// See https://sass-lang.com/documentation/breaking-changes/slash-div

/// Check if math.div exists to assist with compatibility between dart-sass versions
///
/// @example scss
///  @if mq-use-sass-math-for-division() {
///    $size: math.div($px, $base-font-size);
///  } @else {
///    $size: $px / $base-font-size;
///  }
///
/// @returns {bool}
@function mq-use-sass-math-for-division() {
  @return map-has-key(meta.module-functions("math"), "div");
}
```

Used as below, for example in the current `mq-px2em` function:

```
$size: null;
@if mq-use-sass-math-for-division() {
  $size: math.div($px, $base-font-size);
} @else {
  $size: $px / $base-font-size;
}
@return $size * 1em;
```

Perhaps it's overkill to try and support both when the library can just state it requires 2.x when that comes though.

**Comment by area73** [comment]
👋 , @joshdavenport, I though on that too and I like the idea of checking for compatibility , but we will face slightly  same issues because meta.module-functions is available since dart sass 1.23.0 so to me it makes more sense to set the new version not backwards compatible with other sass engines or dart sass prior to 1.34.0 and remove old compatibility with non mediaqueries browsers

**Comment by area73** [comment]
I also found very interesting the use of unit test for this library .
I've been playing with `sass-true` npm package and I'm very happy with the result.
Below is a screen shot of some test that I just run with standar jest for this library

![image](https://user-images.githubusercontent.com/2030605/120114144-19edff80-c17e-11eb-9555-1a86f2400e03.png)


And testing code is writing in `sass` cool 😎

```scss
@use 'true' as *;
@use '_mq' as mq;

@include describe('[function] mq-get-breakpoint-width') {
  @include it('should return the value of a default breakpoint') {
    @include assert-equal(
        mq.mq-get-breakpoint-width('mobile'),
        320px,
        'mobile keyword is defined in breakpoints map'
    );
  }

  @include it('should throw a warn and return null if name is not set in breakpoints map') {
    @include assert-equal(
        mq.mq-get-breakpoint-width('noName'),
        null
    );
  }

  @include describe('given custom breakpoints ') {
    @include it('should return the value of a custom breakpoint') {

        $custom-breakpoints: (
            vga: 640px,
            svga: 800px,
            xga:  1024px,
            uxga:  1600px,
        );

        @include assert-equal(
            mq.mq-get-breakpoint-width('svga',$custom-breakpoints),
            800px
        );
    }
  }

}

@include describe('[function] mq-px2em') {
    @include describe('Given a unitless param'){
        @include it('should throw a warn and return value converted in em') {
            @include assert-equal(
                mq.mq-px2em(16),
                1em,
            );
        }
    }
    @include describe('Given a px param'){
        @include it('should return value converted in em') {
            @include assert-equal(
                mq.mq-px2em(16px),
                1em,
            );
        }
    }
};
```
