### ISSUE TITLE
Remove a useless variable

### ISSUE THREAD

**Issue by KittyGiraudel** [sass-mq/sass-mq#33]
[Here](https://github.com/sass-mq/sass-mq/blob/master/_mq.scss#L235-L236):

``` scss
@mixin mq-add-breakpoint($name, $width) {
    $new-breakpoint: ($name: $width);
    $mq-breakpoints: map-merge($mq-breakpoints, $new-breakpoint) !global;
}
```

Could (should?) be:

``` scss
@mixin mq-add-breakpoint($name, $width) {
    $mq-breakpoints: map-merge($mq-breakpoints, ($name: $width)) !global;
}
```

No need to create an extra variable here.
