### ISSUE TITLE
 Update list using SassScript Maps ?

### ISSUE THREAD

**Issue by magsout** [sass-mq/sass-mq#5]
The new Maps data type in Sass 3.3 is awesome, I think, using it is better ;)

``` scss
$mq-breakpoints: (mobile: 300px , tablet : 600px, desktop :900px, wide :1260px) !default;

@function mq-retrieve-breakpoint-width($name) {
    @each $mq-breakpoint, $breakpoint in $mq-breakpoints {
        $breakpoint-name: #{$mq-breakpoint};
        $breakpoint-width: $breakpoint;

        @if $name == $breakpoint-name {
            @return $breakpoint-width;
        }
    }
    @return 'Breakpoint #{$name} does not exist';
}
```
