### ISSUE TITLE
Split media query string logic into separate function

### ISSUE THREAD

**Issue by NicolajKN** [sass-mq/sass-mq#62]
It would be awesome if the underlying logic could be split out into a separate function. The use case for this would be to support several breakpoints in one media query.

A possible syntax for this could be:

    @media ( #{ mq-string( $from: tablet, $until: desktop ) }, #{ mq-string( $from: 1000px, $until: 1200px ) }  ) {
      ...
    }

Unfortunately is seems the strings **have** to be interpolated to be accepted. I've played around with the syntax here: http://codepen.io/NicolajKN/pen/OVKpjL?editors=110

**Comment by mcaskill** [comment]
If one needs inspiration on how this can be done, my fork splits `mq()` into a _function_ and a _mixin_.

The function contains the brunt of the operations (i.e., chaining of media queries).

The mixin provides the `@media (...) {...}` wrapping.

https://github.com/mcaskill/sass-mq

Using the function:

```
@media ( mq( $from: tablet, $until: desktop, $or: mq( $from: 1000px, $until: 1200px ) ) ) {
  .green {
    background-color: green; 
    color: #fff;
  }
}
```

Using the mixin:

```
@include mq( $from: tablet, $until: desktop, $or: mq( $from: 1000px, $until: 1200px ) ) {
  .green {
    background-color: green; 
    color: #fff;
  }
}
```

**Comment by kaelig** [comment]
Thank you for the suggestion, @NicolajKN.

@mcaskill, cheers for the pointers. I love your fork, you made something really advanced out of sass-mq!

**Comment by kaelig** [comment]
I've looked at how we could extract the logic into a function. Unfortunately it would break consistency between the responsive and non-responsive modes.

Using the function would allow mixing multiple media queries but… would break the contract between the developer and sass-mq that states that loading it with `$mq-responsive: false` works in older browsers.

Thoughts?

**Comment by mcaskill** [comment]
It only breaks the contract if the developer uses the _function_ outside of the _mixin_ when `$mq-responsive: false`. The violation is either voluntary or a mistake. We could throw a `@warn` with a message along the lines of a.

```scss
@warn "When responsive mode is OFF, using the mq() function outside of the mixin is discouraged."
```

Obviously for such an exception to be thrown, we'd need a variable that could track when the function is called outside of the mixin.

```scss
@mixin mq(/* [...] */)
{
	$from-mixin: true;

	@if ($responsive == false) {
		// [...]
	}
	@else {
		$media-query: mq(/* [...] */, $from-mixin);

		@media #{$media-query} {
			@content;
		}
	}
}

@function mq(/* [...] */, $from-mixin: false)
{
	$min-value: 0;
	$max-value: 0;
	$media-query: ();

	@if ($from-mixin == false) and ($responsive == false) {
		@warn "When responsive mode is OFF, using the mq() function outside of the mixin is discouraged.";
	}

	// [...]
}
```

This is a quick solution I could come up with. Obviously, if someone passes `true` to the last parameter of the `mq` function (`$from-mixin`), then they're looking to get the warning.
